server:
  port: 1429
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bych_daxt?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 下面为连接池的补充设置，应用到上面所有数据源中
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
  redis:
      host: 127.0.0.1
      password: ''
      port: 6379
      pool:
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1
      timeout: 0
  jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
  http:
    multipart:
      max-file-size: 4096MB
      max-request-size: 4096MB
#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true
  reasonable: true
  support-methods-arguments: true
  page-size-zero: true
logging:
  config: classpath:logback-dev.xml
#   config: classpath:logback-prodocker.xml

